version: "3.8"

services:
  postgres:
    container_name: "postgres-container"
    image: postgres:14
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_task

  app:
    container_name: "application"
    depends_on:
      - postgres
    image: "app-image"
    environment:
      PG_DSN: postgresql://postgres:1234@postgres:5432/postgres?application_name=postgres&sslmode=disable
    ports:
      - "8000:8000"
    build:
      dockerfile: Dockerfile
    deploy:
      replicas: 1

