version: "3.6"

services:

  postgres-container:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_task
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost



  app:
    image: xyuhya
    ports:
      - "8080:8080"
    build:
      dockerfile: Dockerfile
